# .pre-commit-config.yml
repos:
  # Black: Code Formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # isort: Import Sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # flake8: Linting for PEP 8 and code quality
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88"] # Match Black's default line length

  # pylint: Static Code Analysis
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.2
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        additional_dependencies:
          - requests
          - lxml
          - python-dateutil
